### ISSUE TITLE
butt module regex should not treat numbers the same as punctuation

### ISSUE THREAD

**Issue by le1ca** [wetfish/fishy#3]
https://github.com/wetfish/fishy/blob/master/modules/butt.js#L42

Example of improper behavior:
21:27 < denice> lq, the fist, (level 2 defender) has challenged rachel, the fish, (level 4 defender) to a duel!
21:27 < fishy> lq, the fist, (dick 2 defender) has dongs rachel, the fish, (level **4dicks** defender) to a duel!

**Comment by itsrachelfish** [comment]
Hiya! The treatment of numbers is intentional, to properly preserve IRC color codes. Also, it can can be funny in certain cases...

```
21:38 < denice> pielover88888 misses a blow at rachel.
21:38 < fishy> butt88888 misses a blow at rachel.
```

Anyway, I made [this commit](https://github.com/wetfish/fishy/commit/d0229a47c62f2fdd0291804341ceeefcb26b6003) which prevents non-alphabet characters from being prepended when the entire word consissts of non-alphabet characters.

An example of the new output:

```
22:52  * rachel lq, the fist, (level 2 defender) has challenged rachel, the fish, (level 4 defender) to a duel!
22:52  * fishy lq, dongs fist, (dick 2 defender) has challenged dong, butt butts, (level dick defender) to dongs duel!
```

Thank you :sparkling_heart: :star:
